In [1]:
import boto3
import os
from dotenv import load_dotenv
import pandas as pd
from tqdm import tqdm

# Load environment variables from the .env file
load_dotenv()

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_REGION = os.getenv('AWS_REGION')

## To list files on bucket

In [4]:
# Set up the S3 client
s3_client = boto3.client('s3')

# Define the bucket name
bucket_name = 'beamdata-pocketride'

# Initialize a list to store object details
object_details = []

# Use pagination to list all objects in the bucket
paginator = s3_client.get_paginator('list_objects_v2')
for page in paginator.paginate(Bucket=bucket_name):
    if 'Contents' in page:
        for obj in page['Contents']:
            object_details.append({
                'Key': obj['Key'],
                'LastModified': obj['LastModified'],
                'Size': obj['Size'],
                'ETag': obj['ETag'],
                'StorageClass': obj.get('StorageClass', 'STANDARD')
            })

# Create a DataFrame from the object details list
df = pd.DataFrame(object_details)

In [5]:
df

,Key,LastModified,Size,ETag,StorageClass
0,Chicago/,2024-10-25 20:43:51+00:00,0,"""d41d8cd98f00b204e9800998ecf8427e""",STANDARD
1,Chicago/chicago_weather_data_merged_2024_04.csv,2024-10-28 15:00:02+00:00,2798903440,"""8074a39e06ef6c25578a6c9212c53c8d-163""",STANDARD
2,Chicago/combined_data_2023_05.csv,2024-10-25 20:44:24+00:00,2055432587,"""e8891be1b421c87eb9ef7192e8b42f66-120""",STANDARD
3,Chicago/combined_data_2023_06.csv,2024-10-25 20:56:02+00:00,2060458072,"""8e894520886dc8df6c871d5407ddad40-120""",STANDARD
4,Chicago/combined_data_2023_07.csv,2024-10-25 21:06:49+00:00,2089999718,"""f6068588b0043bae7c7a9de0300ef077-122""",STANDARD
5,Chicago/combined_data_2023_08.csv,2024-10-25 21:06:49+00:00,2107645482,"""97b77c208608318a5348f787b35fb3ad-123""",STANDARD
6,Chicago/combined_data_2023_09.csv,2024-10-25 21:06:49+00:00,2094199535,"""f83821424ade84a7e789426fa1f914b7-122""",STANDARD
7,Chicago/combined_data_2023_10.csv,2024-10-25 21:44:00+00:00,2235188471,"""e63064afe916fabca59bd7e5be4ec970-131""",STANDARD
8,Chicago/combined_data_2023_11.csv,2024-10-25 21:58:51+00:00,2067171465,"""a5d611dd9de553f171939b96979e95ce-247""",STANDARD
9,Chicago/combined_data_2023_12.csv,2024-10-25 22:07:57+00:00,2186040253,"""286e0c800c67d150bdc60ee57bbb5f98-261""",STANDARD
10,Chicago/combined_data_2024_01.csv,2024-10-25 22:16:55+00:00,2088393391,"""e4c9a97887ceaac4ea999715d31d6a93-249""",STANDARD
11,Chicago/combined_data_2024_02.csv,2024-10-25 22:25:42+00:00,2085789317,"""e2324a85bd517bb74d7b04164e29d242-249""",STANDARD
12,Chicago/combined_data_2024_03.csv,2024-10-25 22:34:32+00:00,2361808003,"""462564041f4f5190b612ec05664a6230-282""",STANDARD
13,Chicago/combined_data_2024_04.csv,2024-10-25 22:44:45+00:00,2179063336,"""6a18b9d665604aaaca92c74d98a69129-260""",STANDARD
14,Shared Bike/,2024-10-23 21:40:49+00:00,0,"""d41d8cd98f00b204e9800998ecf8427e""",STANDARD
15,Shared Bike/202409-baywheels-tripdata.csv,2024-10-23 21:42:40+00:00,73522898,"""ca579b52417fb37c1fca103c5ae6127b-5""",STANDARD
16,Shared Bike/Toronto Bikeshare dataset.csv,2024-10-27 15:24:45+00:00,579326257,"""62f3714186bf2dd6f792f749355ee74e-34""",STANDARD
17,Shared Bike/metro-trips-2024-q2.csv,2024-10-23 21:42:40+00:00,19497451,"""a1df1e285279dd046d2e9dbdf921b45f-2""",STANDARD
18,Weather_data/,2024-10-24 00:08:19+00:00,0,"""d41d8cd98f00b204e9800998ecf8427e""",STANDARD
19,Weather_data/NewYork_weather_data.csv,2024-10-24 18:36:39+00:00,567538946,"""fc9cf24fa7b2ffe5632595b32dd755e6-34""",STANDARD
20,Weather_data/chicago_weather_data.csv,2024-10-24 00:08:48+00:00,19611755,"""e78bac56357928e740e64b1104cee2c3-2""",STANDARD
21,Weather_data/toronto_from_Jan_2023_weather_dat...,2024-10-25 19:40:06+00:00,1330881992,"""d904d95a05d834d5de89eea95bec9977-78""",STANDARD
22,Weather_data/toronto_weather_data.csv,2024-10-24 00:08:48+00:00,58438932,"""741befe8e4aa7d830f247e5f0aa5b274-4""",STANDARD
23,test.txt,2024-10-25 19:48:21+00:00,11,"""4221027b3a3f072ba2464439361db5c6""",STANDARD

## Upload or Download Files from S3

In [37]:
s3_client = boto3.client(
    's3',
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    region_name=AWS_REGION
)

def upload_file(file_name, bucket, object_name=None):
    """Upload a file to an S3 bucket."""
    if object_name is None:
        object_name = os.path.basename(file_name)

    try:
        s3_client.upload_file(file_name, bucket, object_name)
        print(f"File '{file_name}' uploaded to bucket '{bucket}' as '{object_name}'.")
    except Exception as e:
        print(f"Error uploading file: {e}")

def download_file(bucket, object_name, file_name):
    """Download a file from an S3 bucket."""
    try:
        s3_client.download_file(bucket, object_name, file_name)
        print(f"File '{object_name}' downloaded from bucket '{bucket}' to '{file_name}'.")
    except Exception as e:
        print(f"Error downloading file: {e}")

# Example usage
if __name__ == "__main__":
    bucket_name = 'beamdata-pocketride'  # Replace with your S3 bucket name

    # Upload a file
    #file_to_upload = r'C:\Users\Richard\Documents\We Cloud Data\Pocketride\test.txt' 
    #upload_file(file_to_upload, bucket_name)

    # Download a file
    #file_to_download = 'test.txt'  # Replace with the file name in S3
    #local_file_name = 'downloaded_file.txt'  # Replace with the local file path
    #download_file(bucket_name, file_to_download, local_file_name)

In [ ]:
# Local directory containing the CSV files
local_directory = r'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024'

# Find all CSV files in the directory
csv_files = glob.glob(os.path.join(local_directory, '*.csv'))

# Upload each CSV file to S3
for file_path in csv_files:
    print(f"Uploading file: {file_path}")
    upload_file_to_s3(file_path, S3_BUCKET)

## Uploading with a folder structure inside S3

In [49]:
bucket_name = 'beamdata-pocketride'
# Define the S3 folder where files will be uploaded
s3_folder = 'Chicago'

class TqdmUploadProgress(tqdm):
    """Custom Tqdm class for monitoring upload progress."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.last_block = 0

    def __call__(self, bytes_amount):
        self.update(bytes_amount - self.last_block)
        self.last_block = bytes_amount

def upload_files_to_s3(file_path, bucket, s3_folder, object_name=None):
    """Uploads a file to a specific folder in an S3 bucket with progress."""
    if object_name is None:
        object_name = os.path.basename(file_path)

    # Construct the S3 object key to include the 'chicago' folder
    s3_key = f"{s3_folder}/{object_name}"

    # Get the file size for progress bar
    file_size = os.path.getsize(file_path)

    # Create a tqdm progress bar
    with TqdmUploadProgress(total=file_size, unit='B', unit_scale=True, desc=file_path, miniters=1) as progress_bar:
        try:
            # Upload file with progress tracking
            s3_client.upload_file(
                file_path,
                bucket,
                s3_key,
                Callback=progress_bar
            )
            print(f"\nSuccessfully uploaded '{file_path}' to bucket '{bucket}/{s3_key}'.")
        except Exception as e:
            print(f"\nFailed to upload '{file_path}': {e}")

# Local directory containing the CSV files
local_directory = r'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024'

# Find all CSV files in the directory
csv_files = glob.glob(os.path.join(local_directory, '*.csv'))



# Upload each CSV file to the 'chicago' folder in S3 with progress tracking
for file_path in csv_files:
    print(f"\nUploading file: {file_path}")
    upload_files_to_s3(file_path, bucket_name, s3_folder)

Uploading file: C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2023_11.csv

C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2023_11.csv:   0%|          | 262k/2.07G [09:06<1196:08:50, 480B/s]

Successfully uploaded 'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2023_11.csv' to bucket 'beamdata-pocketride/Chicago/combined_data_2023_11.csv'.

Uploading file: C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2023_12.csv

C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2023_12.csv:   0%|          | 262k/2.19G [08:58<1247:00:22, 487B/s]

Successfully uploaded 'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2023_12.csv' to bucket 'beamdata-pocketride/Chicago/combined_data_2023_12.csv'.

Uploading file: C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_01.csv

C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_01.csv:   0%|          | 154k/2.09G [08:46<1980:31:19, 293B/s]

Successfully uploaded 'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_01.csv' to bucket 'beamdata-pocketride/Chicago/combined_data_2024_01.csv'.

Uploading file: C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_02.csv

C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_02.csv:   0%|          | 262k/2.09G [08:50<1171:50:36, 494B/s]

Successfully uploaded 'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_02.csv' to bucket 'beamdata-pocketride/Chicago/combined_data_2024_02.csv'.

Uploading file: C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_03.csv

C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_03.csv:   0%|          | 262k/2.36G [10:12<1533:56:56, 428B/s]

Successfully uploaded 'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_03.csv' to bucket 'beamdata-pocketride/Chicago/combined_data_2024_03.csv'.

Uploading file: C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_04.csv

C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_04.csv:   0%|          | 262k/2.18G [09:13<1278:00:50, 474B/s]

Successfully uploaded 'C:\Users\Richard\Documents\We Cloud Data\Pocketride\pocketride\data\chicago\nov_to_apr_2024\combined_data_2024_04.csv' to bucket 'beamdata-pocketride/Chicago/combined_data_2024_04.csv'.

## Concatenating all the files in the folder

In [6]:
directory = 'data/chicago/may_to_oct_2023/may_to_oct_2023_data'

# List all files in the directory
all_files = os.listdir(directory)

# Print each file
for file in all_files:
    print(file)

tnp_data_2023_05_offset_0.csv
tnp_data_2023_05_offset_1000000.csv
tnp_data_2023_05_offset_2000000.csv
tnp_data_2023_05_offset_3000000.csv
tnp_data_2023_05_offset_4000000.csv
tnp_data_2023_05_offset_5000000.csv
tnp_data_2023_05_offset_6000000.csv
tnp_data_2023_06_offset_0.csv
tnp_data_2023_06_offset_1000000.csv
tnp_data_2023_06_offset_2000000.csv
tnp_data_2023_06_offset_3000000.csv
tnp_data_2023_06_offset_4000000.csv
tnp_data_2023_06_offset_5000000.csv
tnp_data_2023_06_offset_6000000.csv
tnp_data_2023_07_offset_0.csv
tnp_data_2023_07_offset_1000000.csv
tnp_data_2023_07_offset_2000000.csv
tnp_data_2023_07_offset_3000000.csv
tnp_data_2023_07_offset_4000000.csv
tnp_data_2023_07_offset_5000000.csv
tnp_data_2023_07_offset_6000000.csv
tnp_data_2023_07_offset_7000000.csv
tnp_data_2023_08_offset_0.csv
tnp_data_2023_08_offset_1000000.csv
tnp_data_2023_08_offset_2000000.csv
tnp_data_2023_08_offset_3000000.csv
tnp_data_2023_08_offset_4000000.csv
tnp_data_2023_08_offset_5000000.csv
tnp_data_2023_08_offset_6000000.csv
tnp_data_2023_08_offset_7000000.csv
tnp_data_2023_09_offset_0.csv
tnp_data_2023_09_offset_1000000.csv
tnp_data_2023_09_offset_2000000.csv
tnp_data_2023_09_offset_3000000.csv
tnp_data_2023_09_offset_4000000.csv
tnp_data_2023_09_offset_5000000.csv
tnp_data_2023_09_offset_6000000.csv
tnp_data_2023_09_offset_7000000.csv
tnp_data_2023_10_offset_0.csv
tnp_data_2023_10_offset_1000000.csv
tnp_data_2023_10_offset_2000000.csv
tnp_data_2023_10_offset_3000000.csv
tnp_data_2023_10_offset_4000000.csv
tnp_data_2023_10_offset_5000000.csv
tnp_data_2023_10_offset_6000000.csv
tnp_data_2023_10_offset_7000000.csv

In [34]:
import pandas as pd
import glob
import re
from pathlib import Path

# Directory containing CSV files
directory = 'data/chicago/nov_to_apr_2024/nov_to_apr_2024_data'
# List all CSV files in the directory
all_files = glob.glob(f'{directory}/*.csv')

# Use a dictionary to group files by year and month
files_by_year_month = {}

# Updated regex pattern to capture year and month
pattern = r'tnp_data_202(\d)_(\d{2})_offset_\d+\.csv'

# Group files by year and month
for file in all_files:
    match = re.search(pattern, file)
    if match:
        year = f"202{match.group(1)}"
        month = match.group(2)
        key = f"{year}_{month}"

        if key not in files_by_year_month:
            files_by_year_month[key] = []
        files_by_year_month[key].append(file)


def concat_files_by_year_month(files, chunksize=100000):
    combined_df = pd.DataFrame()

    for file in files:
        print(f"Processing file: {file}")
        # Read the file in chunks
        for chunk in pd.read_csv(file, chunksize=chunksize):
            combined_df = pd.concat([combined_df, chunk], ignore_index=True)

    return combined_df

In [36]:
for key, files in sorted(files_by_year_month.items()):
    print(f"\nConcatenating files for: {key}")
    year, month = key.split('_')
    monthly_df = concat_files_by_year_month(files)
    
    # Save the concatenated DataFrame to a new CSV file
    output_file = f'data/chicago/nov_to_apr_2024/combined_data_{year}_{month}.csv'
    monthly_df.to_csv(output_file, index=False)
    print(f"Saved combined data for {year}_{month} to {output_file}")

Concatenating files for: 2023_11
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_0.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_1000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_2000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_3000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_4000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_5000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_6000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_11_offset_7000000.csv
Saved combined data for 2023_11 to data/chicago/nov_to_apr_2024/combined_data_2023_11.csv

Concatenating files for: 2023_12
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_0.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_1000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_2000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_3000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_4000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_5000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_6000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2023_12_offset_7000000.csv
Saved combined data for 2023_12 to data/chicago/nov_to_apr_2024/combined_data_2023_12.csv

Concatenating files for: 2024_01
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_0.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_1000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_2000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_3000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_4000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_5000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_6000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_01_offset_7000000.csv
Saved combined data for 2024_01 to data/chicago/nov_to_apr_2024/combined_data_2024_01.csv

Concatenating files for: 2024_02
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_0.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_1000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_2000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_3000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_4000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_5000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_6000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_02_offset_7000000.csv
Saved combined data for 2024_02 to data/chicago/nov_to_apr_2024/combined_data_2024_02.csv

Concatenating files for: 2024_03
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_0.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_1000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_2000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_3000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_4000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_5000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_6000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_03_offset_7000000.csv
Saved combined data for 2024_03 to data/chicago/nov_to_apr_2024/combined_data_2024_03.csv

Concatenating files for: 2024_04
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_0.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_1000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_2000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_3000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_4000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_5000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_6000000.csv
Processing file: data/chicago/nov_to_apr_2024/nov_to_apr_2024_data\tnp_data_2024_04_offset_7000000.csv
Saved combined data for 2024_04 to data/chicago/nov_to_apr_2024/combined_data_2024_04.csv

In [11]:
df=pd.read_csv('data/chicago/may_to_oct_2023/combined_data_2023_05.csv')

In [12]:
df['trip_start_timestamp']

,trip_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,percent_time_chicago,percent_distance_chicago,pickup_census_tract,dropoff_census_tract,pickup_community_area,...,trip_total,shared_trip_authorized,shared_trip_match,trips_pooled,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,a1676a49512c8f0069b1053c95971a46ccf7535e,2023-05-01T00:00:00.000,2023-05-01T00:15:00.000,1687.0,16.5100,1.00060,1.00000,1.703198e+10,1.703181e+10,76.0,...,42.13,False,False,1,41.979071,-87.903040,POINT (-87.9030396611 41.9790708201),NaN,NaN,NaN
1,00142bc9ea520e3d762dfedf42ebc82434504371,2023-05-01T00:00:00.000,2023-05-01T00:45:00.000,2534.0,15.4900,1.00000,1.00000,NaN,NaN,7.0,...,21.23,False,False,1,41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),41.761578,-87.572782,POINT (-87.5727819867 41.7615779081)
2,00963e8460824f53383147bce366b88bb86e98b0,2023-05-01T00:00:00.000,2023-05-01T00:15:00.000,1512.0,21.0200,0.48743,0.46219,NaN,NaN,38.0,...,30.07,False,False,1,41.812949,-87.617860,POINT (-87.6178596758 41.8129489392),NaN,NaN,NaN
3,00de2b6c68baf903734c30087e4a8792557fb044,2023-05-01T00:00:00.000,2023-05-01T00:00:00.000,310.0,1.5200,0.99680,1.00000,1.703184e+10,1.703183e+10,32.0,...,7.52,False,False,1,41.880994,-87.632746,POINT (-87.6327464887 41.8809944707),41.879067,-87.657005,POINT (-87.657005027 41.8790669938)
4,011938f08e56b5aa62079db161887d154357508f,2023-05-01T00:00:00.000,2023-05-01T00:15:00.000,815.0,8.1900,1.00000,1.00000,NaN,NaN,8.0,...,16.23,False,False,1,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.978830,-87.771167,POINT (-87.771166703 41.9788295262)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6985701,ff337bb695e0f8841db8e7eda5f9eca29c3c5932,2023-05-31T23:45:00.000,2023-06-01T00:00:00.000,985.0,6.5299,0.99900,0.99204,NaN,NaN,6.0,...,18.71,False,False,1,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.878866,-87.625192,POINT (-87.6251921424 41.8788655841)
6985702,ff995ca1f3f95da6981e8be2779272d5b2c2e028,2023-05-31T23:45:00.000,2023-05-31T23:45:00.000,438.0,1.0700,1.00000,1.00000,1.703108e+10,1.703108e+10,8.0,...,6.23,False,False,1,41.892042,-87.631864,POINT (-87.6318639497 41.8920421365),41.898332,-87.620763,POINT (-87.6207628651 41.8983317935)
6985703,ffd48cf2919a2496ceb50812e4a67529ea4a4f93,2023-05-31T23:45:00.000,2023-06-01T00:00:00.000,757.0,7.3078,0.99340,1.00000,1.703144e+10,1.703134e+10,44.0,...,13.95,False,False,1,41.748211,-87.610075,POINT (-87.6100749663 41.7482105124),41.827437,-87.632559,POINT (-87.6325587694 41.8274372319)
6985704,fff9a742019f34b869ce6efd9eace2ee87c4d6cf,2023-05-31T23:45:00.000,2023-06-01T00:00:00.000,1042.0,4.1083,0.99520,0.98277,NaN,NaN,50.0,...,20.18,False,False,1,41.706126,-87.598256,POINT (-87.5982558383 41.7061257523),41.763247,-87.616134,POINT (-87.6161341112 41.7632467988)
6985705,fff3d9749178ce146d6064db83155eb23ec4b32d,2023-05-31T23:45:00.000,2023-05-31T23:45:00.000,377.0,2.7850,0.99730,0.98847,1.703128e+10,1.703184e+10,28.0,...,13.31,False,False,1,41.869274,-87.664047,POINT (-87.6640472412 41.8692744531),41.880994,-87.632746,POINT (-87.6327464887 41.8809944707)